# Generated by Django 4.2.5 on 2023-09-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("capacity", models.PositiveIntegerField(db_index=True)),
                ("price_per_night", models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ("meta", models.JSONField(default=dict)),
                ("status", models.PositiveSmallIntegerField(choices=[(1, "Active"), (2, "Inactive")], db_index=True)),
            ],
        ),
    ]
